name: clock
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  circular_countdown_timer: ^0.2.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  solandra: ^0.0.4

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false
